"""empty message

Revision ID: ecc107e4e3b0
Revises: b61d4a1d56a7
Create Date: 2022-02-13 20:31:09.952600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc107e4e3b0'
down_revision = 'b61d4a1d56a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'amount')
    # ### end Alembic commands ###
